var T = {
  undefinedFormat: 'Diese Datei wurde nicht erkannt.',
  camt53V4: 'camt.053 (V4) Datei',
  camt54V4: 'camt.054 (V4) Datei',
  fileName: 'Datei',
  creationDate: 'Erstellt am',
  customerAccount: 'Kundenkonto',
  transactions: 'Transaktionen',
  transactionsNo: 'Anzahl der Transaktionen',
  incomesNo: 'Anzahl des ESR',
  openBalance: 'Eröffnungssaldo',
  closeBalance: 'Abschlusssaldo',
  dateValuta: 'Valuta',
  dateBooking: 'Bunchungsdatum',
  totalCharge: 'Gesamtkosten',
  total: 'Gesamtbetrag',
  movement: 'Bewegung',
  debtor: 'Debitor',
  finInstitute: 'Finanzinstitut',
  reference: 'Referenz',
  charges: 'Kosten',
  amount: 'Betrag',
};
